
Neos:
  Flow:
    mvc:
      routes:
        Sandstorm.MxGraph: true
    security:
      authentication:
        providers:
          Typo3BackendProvider:
            requestPatterns:
              'Sandstorm.MxGraph:backend':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sandstorm\MxGraph\Controller\.*'
  Neos:
    userInterface:
      requireJsPathMapping:
        Sandstorm.MxGraph/Editors: 'resource://Sandstorm.MxGraph/Public/Scripts/Inspector/Editors'
    fusion:
      autoInclude:
        Sandstorm.MxGraph: true
